# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5c298b92a37abbcfb777a4aedc6ae8d231d0a6d7c132ef232b0b4c8614df989854e368db1736401f2d19809e7503ca9b5f7c91b7d7ac1910ca8cf8092d631d1

test:
  secret_key_base: d6a68c3d7eda810025bc3b16a8473f403e0c5d38c36ec1b6916af687e0155a5a9a23d11c3ab99509af6a4a98fb627484449f1e1c008ea661c431cf419034c725

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
